---
prod_server:
  hosts:
    monitoring:
      ansible_host: 77.105.185.194
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

    node_exporter1:
      ansible_host: 91.185.85.111
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

    node_exporter2:
      ansible_host: 91.185.85.136
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

    node_exporter3:
      ansible_host: 91.185.85.221
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

    node_exporter4:
      ansible_host: 91.185.85.228
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

    node_exporter5:
      ansible_host: 77.105.185.143
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3