---
prod_server:
  hosts:
    monitoring:
      ansible_host: 77.105.185.143
      ansible_user: alexblacknn
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3

