{
 "title": "4 Golden Signals",
 "tags": [ "nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}, ingress) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per-container CPU usage in CPU cores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!~\"POD|\", namespace=\"sre-cource-student-107\"}[5m])) by (namespace,pod,container)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Per-container CPU usage in CPU cores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!~\"POD|\", namespace=\"sre-cource-student-107\"}[5m])) by (pod,container)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Per-node CPU usage in CPU cores:",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace=\"sre-cource-student-107\"}[5m])) by (node)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Per-container memory usage in MB:",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "memory (MB)" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!~\"POD|\", namespace=\"sre-cource-student-107\"}) by (namespace,pod,container)/(1024 * 1024)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Per-pod memory usage in MB:",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "memory (MB)" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",namespace=\"sre-cource-student-107\"}) by (namespace,pod) / (1024 * 1024)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Per-node memory usage in MB:",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "memory (MB)" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",namespace=\"sre-cource-student-107\"}) by (node) / (1024 * 1024)",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\", namespace=\"sre-cource-student-107\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\" ,status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) "
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\" ,status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (4xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\" ,status=~\"[4**].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\" ,status=~\"[5**].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  { "title": "Trafic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Average Ingress Request Volume",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{exported_namespace=\"sre-cource-student-107\",ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table-old",
   "description": "This data is real time, independent of dashboard time range",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le, ingress, status))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le, ingress, status))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le, ingress, status))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{exported_namespace=\"sre-cource-student-107\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{exported_namespace=\"sre-cource-student-107\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Request Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le, ingress))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le, ingress))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"sre-cource-student-107\"}[2m])) by (le, ingress))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}