services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpasswordpassword
      - DOCKER_INFLUXDB_INIT_ORG=demo_org
      - DOCKER_INFLUXDB_INIT_BUCKET=demo_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=demo_token
