---
- hosts: monitoring
  become: yes
  roles:
  - prometheus
  - alertmanager
  - blackbox_exporter
  vars:
    prometheus_targets:
      node:
      - targets:
        - node.demo.do.prometheus.io
        labels:
          name: node.proprometheus
      etcd:
        - targets:
            - 10.0.10.2:2379
            - 10.0.10.3:2379
            - 10.0.10.4:2379
          labels:
            name: etcd
      node_exporter:
        - targets:
            - 10.0.10.2:9100
            - 10.0.10.3:9100
            - 10.0.10.4:9100
            - 10.0.10.5:9100
            - 10.0.10.6:9100
          labels:
            name: node_exporter
      black_box:
        - targets:
            - localhost:9115
          labels:
            name: black_box
      patroni_exporter:
        - targets:
            - 10.0.10.5:8008
            - 10.0.10.6:8008
          labels:
            name: patroni_exporter
      postgres_exporter:
        - targets:
            - 10.0.10.5:9187
            - 10.0.10.6:9187
          labels:
            name: postgres_exporter


    alertmanager_version: latest
    alertmanager_slack_api_url: "http://example.com"
    alertmanager_receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
    alertmanager_route:
      group_by: [ 'alertname', 'cluster', 'service' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: slack

- hosts: pc_with_node_exporters
  become: yes
  roles:
    - node_exporter

- hosts: pc_with_docker_patroni_exporter_postgres_exporter
  become: yes
  roles:
    - docker
    - patroni_exporter
    - postgres_exporter
