---
- hosts: monitoring
  become: yes
  roles:
  - prometheus
  - alertmanager
  - blackbox_exporter
  vars:
    prometheus_targets:
      node:
      - targets:
        - node.demo.do.prometheus.io
        - 10.0.10.2:2379
        - 10.0.10.3:2379
        - 10.0.10.4:2379
        - 10.0.10.2:9100
        - 10.0.10.3:9100
        - 10.0.10.4:9100
        - 10.0.10.5:9100
        - 10.0.10.6:9100
        - localhost:9115
        labels:
          env: demosite

    alertmanager_version: latest
    alertmanager_slack_api_url: "http://example.com"
    alertmanager_receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
    alertmanager_route:
      group_by: [ 'alertname', 'cluster', 'service' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: slack

- hosts: node_exporter1
  become: yes
  roles:
    - node_exporter

- hosts: node_exporter2
  become: yes
  roles:
    - node_exporter

- hosts: node_exporter3
  become: yes
  roles:
    - node_exporter

- hosts: node_exporter4
  become: yes
  roles:
    - node_exporter

- hosts: node_exporter5
  become: yes
  roles:
    - node_exporter
