image:
  repository: ghcr.io/ldest/sre-course/api
  tag: "c4f3862"
imagePullPolicy: IfNotPresent
replicas: 1
service:
  port: 80
  servicePort: 80
revisionHistoryLimit: 15
strategy:
  type:  RollingUpdate
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 20%
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 6
  path: /healthz/live
  tcp_port: 80
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 6
  path: /healthz/ready
  tcp_port: 80
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
hpa:
  metrics:
    CpuAverageUtilization: 80
  minReplicas: 1
  maxReplicas: 2

