# Только для тестового запуска. Внимание: порт в БД открыт.
# переменная DOTNET_ENVIRONMENT = Development - режим разрботки
# swagger в таком режиме будет включен и доступен по
# http://127.0.0.1:8001/swagger/index.html

version: "3.7"
services:
  db:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/:/var/lib/postgresql/data/
    env_file:
      - ./.env

  app:
    image: ghcr.io/ldest/sre-course/api:0e6cd26
    environment:
      - DOTNET_ENVIRONMENT="Development"
      - ConnectionStrings__PgConnection=Server=db;Database=postgres;User Id=postgres;Password=postgres;
    ports:
      - "8001:80"