---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.path }}
        backend:
          service:
            name: {{ .Values.service }}
            port:
              number: {{ .Values.port_number }}
 