---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{.Values.replicas}}
  revisionHistoryLimit: {{.Values.revisionHistoryLimit}}
  # Стратегия развёртывания.
  # RollingUpdate, которая будет обновлять Pod'ы порциями
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{.Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
          env:
            - name: "DOTNET_ENVIRONMENT"
              value: "Development"
            - name: "ConnectionStrings__PgConnection"
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: PgConnection
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
