---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
data:
  PgConnection: U2VydmVyPTkxLjE4NS44NC4xNTM7UG9ydD01MDAwO0RhdGFiYXNlPXBvc3RncmVzO1VzZXIgSWQ9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXMtcGFzczs=
type: Opaque
